# This is a basic workflow to help you get started with Actions

name: SIGNINJUEJIN

# Controls when the workflow will run
on:
  push:
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Install node'
        uses: actions/setup-node@v1
      - name: 'Install NPM dependencies'
        run: npm install
      - name: 'Run code'
        run: node index.js
        env:
          AID: ${{ secrets.AID }}
          UUID: ${{ secrets.UUID }}
          TOKEN: ${{ secrets.TOKEN }}
          COOKIE: ${{ secrets.COOKIE }}

